// POST EMPLOYEE DATA
export const POST_EMPLOYEE_DATA = "POST_EMPLOYEE_DATA";
export const POST_EMPLOYEE_DATA_SUCCESS = "POST_EMPLOYEE_DATA_SUCCESS";
export const POST_EMPLOYEE_DATA_FAILURE = "POST_EMPLOYEE_DATA_FAILURE";

//GET EMPLOYEE DATA
export const GET_EMPLOYEE_DATA = "GET_EMPLOYEE_DATA";
export const GET_EMPLOYEE_DATA_SUCCESS = "GET_EMPLOYEE_DATA_SUCCESS";
export const GET_EMPLOYEE_DATA_FAILURE = "GET_EMPLOYEE_DATA_FAILURE";

//DELETE EMPLOYEE DATA
export const DELETE_EMPLOYEE_DATA = "DELETE_EMPLOYEE_DATA";
export const DELETE_EMPLOYEE_DATA_SUCCESS = "DELETE_EMPLOYEE_DATA_SUCCESS";
export const DELETE_EMPLOYEE_DATA_FAILURE = "DELETE_EMPLOYEE_DATA_FAILURE";

//EDIT EMPLOYEE DATA
export const EDIT_EMPLOYEE_DATA = "EDIT_EMPLOYEE_DATA";
export const EDIT_EMPLOYEE_DATA_SUCCESS = "EDIT_EMPLOYEE_DATA_SUCCESS";
export const EDIT_EMPLOYEE_DATA_FAILURE = "EDIT_EMPLOYEE_DATA_FAILURE";